name: sonar-release
# This workflow is triggered when publishing a GitHub release
on:
  release:
    types:
      - published

jobs:
  sonar_release:
    runs-on: ubuntu-latest
    name: Start release process
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@d42e8be3a9772d0447a7d2f3d2be31312b218383  # tag=5.0.1
    with:
      publishToBinaries: false
      mavenCentralSync: true
      slackChannel: team-sonarqube-build
